# Generated by Django 2.2 on 2019-07-12 04:46

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maplas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
