# Generated by Django 2.2 on 2019-07-12 05:12

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maplas_app', '0002_track_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='color',
            field=colorfield.fields.ColorField(blank=True, max_length=18, null=True),
        ),
    ]
