# Generated by Django 2.2 on 2019-08-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maplas_app', '0006_auto_20190822_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='gpx_file',
            field=models.TextField(blank=True, default=''),
        ),
    ]
