# Generated by Django 2.2 on 2019-09-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maplas_app', '0007_track_gpx_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='points_json',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='track',
            name='points_json_optimized',
            field=models.TextField(blank=True, default=''),
        ),
    ]
