# Generated by Django 2.2 on 2019-09-24 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maplas_app', '0009_track_upload_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maplas_app.Place'),
        ),
    ]
