# Generated by Django 2.2 on 2019-09-25 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maplas_app', '0010_auto_20190924_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackDetails',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('maplas_app.track',),
        ),
    ]
