# Generated by Django 2.2 on 2020-04-13 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maplas_app', '0011_trackdetails'),
    ]

    atomic = False

    operations = [
        migrations.RenameModel(
            old_name='Place',
            new_name='Region',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='place',
            new_name='region',
        ),
    ]
