# Generated by Django 2.2 on 2020-06-09 08:03

from django.db import migrations, models
import django.db.models.deletion
import maplas_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('maplas_app', '0014_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=maplas_app.models.Photo.get_file_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maplas_app.Place'),
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('lat', 'lon')},
        ),
    ]
