# Generated by Django 2.2 on 2020-06-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maplas_app', '0015_auto_20200609_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='exif_time_taken',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
