# Generated by Django 2.2 on 2020-07-12 08:29

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maplas_app', '0018_place_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, default='')),
                ('points_json', models.TextField(blank=True, default='')),
                ('color', colorfield.fields.ColorField(blank=True, max_length=18, null=True)),
            ],
        ),
    ]
