# Generated by Django 2.2 on 2020-07-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maplas_app', '0019_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='tile_indexes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
