# Generated by Django 2.2 on 2021-03-09 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maplas_app', '0021_auto_20210308_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='lat',
            new_name='exif_lat',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='lon',
            new_name='exif_lon',
        ),
    ]
