# Generated by Django 2.2 on 2021-03-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maplas_app', '0022_auto_20210309_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='photo',
            name='private',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
