# Generated by Django 2.2 on 2022-11-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maplas_app', '0024_auto_20221103_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='placetype',
            name='icon',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
