# Generated by Django 2.2 on 2022-11-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maplas_app', '0025_placetype_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disabled', models.BooleanField(blank=True)),
                ('order', models.IntegerField()),
                ('dict_key', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('javascript_code', models.CharField(max_length=10000)),
            ],
        ),
    ]
