# Generated by Django 2.2 on 2022-11-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maplas_app', '0026_maplayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maplayer',
            name='javascript_code',
            field=models.TextField(),
        ),
    ]
