# Generated by Django 2.2 on 2022-11-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maplas_app', '0027_auto_20221107_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maplayer',
            name='disabled',
        ),
        migrations.AddField(
            model_name='maplayer',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
