# Generated by Django 2.2 on 2024-09-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maplas_app', '0029_videolink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placetype',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='placetype',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
