# Generated by Django 2.2 on 2024-09-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maplas_app', '0030_auto_20240905_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='StringField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=1000)),
                ('value', models.TextField(blank=True)),
            ],
        ),
    ]
