# Generated by Django 2.2 on 2024-09-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maplas_app', '0031_stringfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='photo',
            name='order',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='past',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
