# Generated by Django 2.2 on 2024-09-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maplas_app', '0033_track_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='status',
            field=models.IntegerField(choices=[(1, 'done'), (2, 'planned'), (3, 'trail'), (4, 'other people'), (5, 'event'), (6, 'border')]),
        ),
        migrations.AlterField(
            model_name='track',
            name='type',
            field=models.IntegerField(choices=[(1, 'car'), (2, 'bicycle'), (3, 'walk'), (4, 'other'), (5, 'mushroom')]),
        ),
    ]
