# Generated by Django 2.2 on 2024-09-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maplas_app', '0034_auto_20240915_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='GpsPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('time', models.DateTimeField(db_index=True)),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
    ]
