# Generated by Django 2.2 on 2024-09-18 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maplas_app', '0035_gpspoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceTypeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pl', models.CharField(max_length=100)),
                ('en', models.CharField(max_length=100)),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='placetype',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='maplas_app.PlaceTypeGroup'),
        ),
    ]
