# Generated by Django 2.2 on 2025-04-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maplas_app', '0036_auto_20240918_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplayer',
            name='type',
            field=models.CharField(choices=[('base', 'base'), ('overlay', 'overlay')], default='base', max_length=100),
            preserve_default=False,
        ),
    ]
